version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    volumes:
      - final_project_mssql:/var/opt/mssql/data
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
volumes:
  final_project_mssql:
