version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    volumes:
      - final_project_mssql:/var/opt/mssql/data
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ../backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8.1-fpm-bullseye
    volumes:
      - ../backend:/var/www/html
volumes:
  final_project_mssql:
